name: colette_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  intl: ^0.17.0
  equatable: ^2.0.3
  formz: ^0.4.1
  bloc_test: ^9.0.1
  mocktail: ^0.3.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
